modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/jamlib/issues"

[[mods]]
modId = "jamlib"
version = "${version}"
displayName = "JamLib"
displayURL = "https://github.com/JamCoreModding/jamlib"
logoFile = "icon.png"
authors = "Jamalam"
description = '''The platform-agnostic library used in all of JamCore's mods'''

[[dependencies.jamlib]]
modId = "forge"
mandatory = true
versionRange = "[47.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jamlib]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jamlib]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"
