modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/jamlib/issues"

[[mods]]
modId = "testmod"
version = "${file.jarVersion}"
displayName = "JamLib Test Mod"
displayURL = "https://github.com/JamCoreModding/jamlib"
logoFile = "icon.png"
authors = "Jamalam"
description = '''Test Mod for JamLib'''
