name: build

on:
  - push
  - pull_request

jobs:
  build:
    uses: JamCoreModding/.github/.github/workflows/mod.yml@main
    with:
      java-version: 17
      build-tasks: 'clean forge:build fabric:build'
